version: "3.8"

services:
  # Video API Application
  api:
    build: .
    container_name: video_api_app
    environment:
      - NODE_ENV=development
      - PORT=3000
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
      - JWT_EXPIRES_IN=24h
      - UPLOAD_PATH=./uploads
      - PROCESSED_PATH=./processed
      - MAX_FILE_SIZE=500MB
      - CPU_MONITORING_INTERVAL=1000
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/app/uploads
      - ./processed:/app/processed
    depends_on: {}
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes: {}
