services:
  # Video API Application
  api:
    build: .
    container_name: video_api_app
    environment:
      - NODE_ENV=development
      - PORT=3000
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
      - JWT_EXPIRES_IN=24h
      - UPLOAD_PATH=./uploads
      - PROCESSED_PATH=./processed
      - MAX_FILE_SIZE=500MB
      - CPU_MONITORING_INTERVAL=1000
      - ASSEMBLYAI_API_KEY=0f9a5e8206e947bc91d6349b368811b2
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/app/uploads
      - ./processed:/app/processed
    depends_on: {}
    healthcheck:
      test: ["CMD-SHELL", "node -e \"require('http').get('http://localhost:3000/health', r => process.exit(r.statusCode===200?0:1))\" "]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Load generator using k6 to drive CPU test for 5 minutes
  load:
    image: grafana/k6:0.49.0
    container_name: video_api_load
    depends_on:
      api:
        condition: service_healthy
    environment:
      - K6_OUT=csv=/scripts/k6_results.csv
      - API_BASE=http://api:3000
      - AUTH_TOKEN=REPLACE_WITH_YOUR_TOKEN
      - TEST_DURATION=5m
      - VUS=25
    volumes:
      - ./scripts:/scripts
    entrypoint: ["k6", "run", "/scripts/test-cpu.js"]

volumes: {}
